// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Rental struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UserID     uuid.UUID
	TapeID     uuid.UUID
	RentedAt   time.Time
	ReturnedAt sql.NullTime
}

type Tape struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Director  string
	Genre     string
	Quantity  int32
	Price     float64
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
}
