// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Rental struct {
	ID         int32
	PublicID   uuid.NullUUID
	CreatedAt  time.Time
	UserID     int32
	TapeID     int32
	RentedAt   time.Time
	ReturnedAt sql.NullTime
}

type Tape struct {
	ID        int32
	PublicID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Director  string
	Genre     string
	Quantity  int32
	Price     float64
}

type User struct {
	ID        int32
	PublicID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Email     string
}
