// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tapes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTape = `-- name: CreateTape :one
INSERT INTO tapes (id, created_at, updated_at, title, director, genre, quantity, price)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, created_at, updated_at, title, director, genre, quantity, price
`

type CreateTapeParams struct {
	Title    string
	Director string
	Genre    string
	Quantity int32
	Price    int32
}

func (q *Queries) CreateTape(ctx context.Context, arg CreateTapeParams) (Tape, error) {
	row := q.db.QueryRowContext(ctx, createTape,
		arg.Title,
		arg.Director,
		arg.Genre,
		arg.Quantity,
		arg.Price,
	)
	var i Tape
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Director,
		&i.Genre,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getTape = `-- name: GetTape :one
SELECT id, created_at, updated_at, title, director, genre, quantity, price FROM tapes
WHERE id = $1
`

func (q *Queries) GetTape(ctx context.Context, id uuid.UUID) (Tape, error) {
	row := q.db.QueryRowContext(ctx, getTape, id)
	var i Tape
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Director,
		&i.Genre,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getTapes = `-- name: GetTapes :many
SELECT id, created_at, updated_at, title, director, genre, quantity, price FROM tapes
ORDER BY created_at ASC
`

func (q *Queries) GetTapes(ctx context.Context) ([]Tape, error) {
	rows, err := q.db.QueryContext(ctx, getTapes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tape
	for rows.Next() {
		var i Tape
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Director,
			&i.Genre,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
