// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tapes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTape = `-- name: CreateTape :one
INSERT INTO tapes (title, director, genre, quantity, price)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, public_id, created_at, updated_at, title, director, genre, quantity, price
`

type CreateTapeParams struct {
	Title    string
	Director string
	Genre    string
	Quantity int32
	Price    float64
}

func (q *Queries) CreateTape(ctx context.Context, arg CreateTapeParams) (Tape, error) {
	row := q.db.QueryRowContext(ctx, createTape,
		arg.Title,
		arg.Director,
		arg.Genre,
		arg.Quantity,
		arg.Price,
	)
	var i Tape
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Director,
		&i.Genre,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const deleteAllTapes = `-- name: DeleteAllTapes :exec
DELETE FROM tapes
`

func (q *Queries) DeleteAllTapes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTapes)
	return err
}

const deleteTape = `-- name: DeleteTape :exec
DELETE FROM tapes
WHERE id = $1
`

func (q *Queries) DeleteTape(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTape, id)
	return err
}

const getTapeByID = `-- name: GetTapeByID :one
SELECT id, public_id, created_at, updated_at, title, director, genre, quantity, price FROM tapes
WHERE id = $1
`

func (q *Queries) GetTapeByID(ctx context.Context, id int32) (Tape, error) {
	row := q.db.QueryRowContext(ctx, getTapeByID, id)
	var i Tape
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Director,
		&i.Genre,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getTapeFromPublicID = `-- name: GetTapeFromPublicID :one
SELECT id, public_id, created_at, updated_at, title, director, genre, quantity, price FROM tapes
WHERE public_id = $1
`

func (q *Queries) GetTapeFromPublicID(ctx context.Context, publicID uuid.UUID) (Tape, error) {
	row := q.db.QueryRowContext(ctx, getTapeFromPublicID, publicID)
	var i Tape
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Director,
		&i.Genre,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getTapes = `-- name: GetTapes :many
SELECT id, public_id, created_at, updated_at, title, director, genre, quantity, price FROM tapes
ORDER BY created_at ASC
`

func (q *Queries) GetTapes(ctx context.Context) ([]Tape, error) {
	rows, err := q.db.QueryContext(ctx, getTapes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tape
	for rows.Next() {
		var i Tape
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Director,
			&i.Genre,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTape = `-- name: UpdateTape :one
UPDATE tapes
SET
  updated_at =  NOW(),
  title =       COALESCE($2, title),
  director =    COALESCE($3, director),
  genre =       COALESCE($4, genre),
  quantity =    COALESCE($5, quantity),
  price =       COALESCE($6, price)
WHERE id = $1
RETURNING id, public_id, created_at, updated_at, title, director, genre, quantity, price
`

type UpdateTapeParams struct {
	ID       int32
	Title    sql.NullString
	Director sql.NullString
	Genre    sql.NullString
	Quantity sql.NullInt32
	Price    sql.NullFloat64
}

func (q *Queries) UpdateTape(ctx context.Context, arg UpdateTapeParams) (Tape, error) {
	row := q.db.QueryRowContext(ctx, updateTape,
		arg.ID,
		arg.Title,
		arg.Director,
		arg.Genre,
		arg.Quantity,
		arg.Price,
	)
	var i Tape
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Director,
		&i.Genre,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}
