FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . /app

RUN CGO_ENABLED=0 GOOS=linux go build -o server /app

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server /app

EXPOSE 8080

CMD ["/app/server"]


